#ifndef __APPLICATION_DATACOLLECTION_H_
#define __APPLICATION_DATACOLLECTION_H_

#include "../../app-conf.h"

#ifndef COMPONENT_APPLICATION_DATACOLLECTION_MESSAGESIZE
#define COMPONENT_APPLICATION_DATACOLLECTION_MESSAGESIZE 10
#endif

#ifndef COMPONENT_APPLICATION_DATACOLLECTION_INTERVALSEND_MIN
#define COMPONENT_APPLICATION_DATACOLLECTION_INTERVALSEND_MIN 30
#endif

#ifndef COMPONENT_APPLICATION_DATACOLLECTION_INTERVALSEND_MAX
#define COMPONENT_APPLICATION_DATACOLLECTION_INTERVALSEND_MAX 60
#endif

#endif /* __APPLICATION_DATACOLLECTION_H_ */
