#ifndef __POWERCONTROL_CALIBRATED_H_
#define __POWERCONTROL_CALIBRATED_H_

#ifndef COMPONENT_POWERCONTROL_CALIBRATED_SAFETYMARGIN
#define COMPONENT_POWERCONTROL_CALIBRATED_SAFETYMARGIN 0.2
#endif

#endif /* __POWERCONTROL_CALIBRATED_H_ */
