#ifndef __POWERCONTROL_ADAPTIVE_H_
#define __POWERCONTROL_ADAPTIVE_H_

#include "../../app-conf.h"

#ifndef COMPONENT_POWERCONTROL_ADAPTIVE_UPDATEINTERVAL
#define COMPONENT_POWERCONTROL_ADAPTIVE_UPDATEINTERVAL 600
#endif

#ifndef COMPONENT_POWERCONTROL_ADAPTIVE_RATIO
#define COMPONENT_POWERCONTROL_ADAPTIVE_RATIO 0.9
#endif

#ifndef COMPONENT_POWERCONTROL_ADAPTIVE_MESSAGES
#define COMPONENT_POWERCONTROL_ADAPTIVE_MESSAGES 20
#endif

#ifndef COMPONENT_POWERCONTROL_ADAPTIVE_CONSECUTIVEFAILED
#define COMPONENT_POWERCONTROL_ADAPTIVE_CONSECUTIVEFAILED 3
#endif

#ifndef COMPONENT_POWERCONTROL_ADAPTIVE_OPTIMIZATIONPERCENT
#define COMPONENT_POWERCONTROL_ADAPTIVE_OPTIMIZATIONPERCENT 0.1
#endif


#endif /* __POWERCONTROL_ADAPTIVE_H_ */
