#ifndef __APP_CONF_H_
#define __APP_CONF_H_

#include "app-conf-constants.h"

#define COMPONENT_NETWORKSTACK_IPV6_ROOTNODE 1

#define COMPONENT_APPLICATION_DATACOLLECTION_SINK_RIME "1.0"
#define COMPONENT_APPLICATION_DATACOLLECTION_SINK_IPV6 "aaaa::0212:7401:0001:0101"

#define COMPONENT_APPLICATION_MESHMESSAGES_NODESLIST_RIME "1.0,2.0,3.0,4.0,6.0,7.0,8.0,10.0,15.0,11.0,14.0,13.0,16.0,17.0,18.0,19.0,20.0,22.0,23.0,25.0,26.0,27.0,28.0,31.0,33.0,32.0"

#define COMPONENT_APPLICATION       COMPONENT_APPLICATION_MESHMESSAGES
#define COMPONENT_NEIGHBORDISCOVERY COMPONENT_NEIGHBORDISCOVERY_NULL
#define COMPONENT_NETWORKSTACK      COMPONENT_NETWORKSTACK_RIME
#define COMPONENT_NETWORKSTACK_MODE COMPONENT_NETWORKSTACK_MODE_MESH
#define COMPONENT_POWERCONTROL      COMPONENT_POWERCONTROL_NULL
#define COMPONENT_RADIO             COMPONENT_RADIO_AUTODETECT
#define COMPONENT_TOPOLOGYCONTROL   COMPONENT_TOPOLOGYCONTROL_NULL
#define APP_PRINT_EVALUATION 1

#define UTILITIES_CONTIKIRANDOM_STATICSEED 123456
#define UTILITIES_CONTIKIRANDOM_SEED UTILITIES_CONTIKIRANDOM_SEED_RANDOM

#endif /* __APP_CONF_H_ */
