#ifndef __APP_CONF_H_
#define __APP_CONF_H_

#include "app-conf-constants.h"

#define COMPONENT_NETWORKSTACK_IPV6_ROOTNODE 1

#define COMPONENT_APPLICATION_DATACOLLECTION_SINK_RIME "1.0"
#define COMPONENT_APPLICATION_DATACOLLECTION_SINK_IPV6 "aaaa::0212:7401:0001:0101"

#define COMPONENT_APPLICATION_MESHMESSAGES_NODESLIST_RIME "1.0,2.0,3.0"

#define COMPONENT_APPLICATION       ...
#define COMPONENT_NEIGHBORDISCOVERY ...
#define COMPONENT_NETWORKSTACK      COMPONENT_NETWORKSTACK_MAKEFILE
#define COMPONENT_NETWORKSTACK_MODE ...
#define COMPONENT_POWERCONTROL      ...
#define COMPONENT_RADIO             COMPONENT_RADIO_AUTODETECT
#define COMPONENT_TOPOLOGYCONTROL   ...

#define UTILITIES_CONTIKIRANDOM_STATICSEED 123456
#define UTILITIES_CONTIKIRANDOM_SEED UTILITIES_CONTIKIRANDOM_SEED_STATIC

#endif /* __APP_CONF_H_ */
