#ifndef __APP_CONF_H_
#define __APP_CONF_H_

#include "app-conf-constants.h"

#define COMPONENT_NETWORKSTACK_IPV6_ROOTNODE 1

#define COMPONENT_APPLICATION_DATACOLLECTION_SINK_RIME "251.3"
#define COMPONENT_APPLICATION_DATACOLLECTION_SINK_IPV6 "aaaa::0212:7401:0001:0101"

#define COMPONENT_APPLICATION_MESHMESSAGES_NODESLIST_RIME "241.3,27.4,253.3,2.4,22.4,242.3,244.3,250.3,0.4,8.4,10.4,251.3,1.4,9.4,246.3,11.4,6.4"

#define COMPONENT_APPLICATION       COMPONENT_APPLICATION_DATACOLLECTION
#define COMPONENT_NEIGHBORDISCOVERY COMPONENT_NEIGHBORDISCOVERY_NULL
#define COMPONENT_NETWORKSTACK      COMPONENT_NETWORKSTACK_RIME
#define COMPONENT_NETWORKSTACK_MODE COMPONENT_NETWORKSTACK_MODE_MESH
#define COMPONENT_POWERCONTROL      COMPONENT_POWERCONTROL_NULL
#define COMPONENT_RADIO             COMPONENT_RADIO_AUTODETECT
#define COMPONENT_TOPOLOGYCONTROL   COMPONENT_TOPOLOGYCONTROL_NULL
#define APP_PRINT_EVALUATION 1

#define UTILITIES_CONTIKIRANDOM_STATICSEED 123456
#define UTILITIES_CONTIKIRANDOM_SEED UTILITIES_CONTIKIRANDOM_SEED_RANDOM

#endif /* __APP_CONF_H_ */
