#ifndef __APP_CONF_CONSTANTS_H_
#define __APP_CONF_CONSTANTS_H_

#define COMPONENT_APPLICATION_NULL 0
#define COMPONENT_APPLICATION_DATACOLLECTION 1
#define COMPONENT_APPLICATION_MESHMESSAGES 2
#define COMPONENT_APPLICATION_RANDOMWALK 3
#define COMPONENT_APPLICATION_POWERCALIBRATION 4

#define COMPONENT_NEIGHBORDISCOVERY_NULL 0
#define COMPONENT_NEIGHBORDISCOVERY_TWOHOPBROADCAST 1

#define COMPONENT_NETWORKSTACK_MAKEFILE 1
#define COMPONENT_NETWORKSTACK_IPV6 2
#define COMPONENT_NETWORKSTACK_RIME 3
#define COMPONENT_NETWORKSTACK_MODE_MESH 1
#define COMPONENT_NETWORKSTACK_MODE_SINK 2

#define COMPONENT_POWERCONTROL_NULL 0
#define COMPONENT_POWERCONTROL_BINARYSEARCH 1
#define COMPONENT_POWERCONTROL_CALIBRATED 2
#define COMPONENT_POWERCONTROL_PTPC 3

#define COMPONENT_RADIO_AUTODETECT 1
#define COMPONENT_RADIO_CC2420 2
#define COMPONENT_RADIO_CC2520 3
#define COMPONENT_RADIO_COOJA 4

#define COMPONENT_TOPOLOGYCONTROL_NULL 0
#define COMPONENT_TOPOLOGYCONTROL_AKTC 1
#define COMPONENT_TOPOLOGYCONTROL_LKTC 2
#define COMPONENT_TOPOLOGYCONTROL_PKTC 3

#define UTILITIES_CONTIKIRANDOM_SEED_STATIC 1
#define UTILITIES_CONTIKIRANDOM_SEED_RANDOM 2

#endif /* __APP_CONF_CONSTANTS_H_ */
